### ISSUE TITLE
Roundcube-Aliases crash

### ISSUE THREAD

**Issue by erdoking** [gianlucagiacometti/Roundcube-Aliases#2]
Hi all,

i try the plugin on my roundcube instance, but all times i get  "HTTP ERROR 500".

My steps:

cd /var/www/roundcubemail/plugins/
git checkout https://github.com/gianlucagiacometti/Roundcube-Aliases aliases
chown -R www-data:www-data aliases
cp aliases/config.inc.php.dist aliases/config.inc.php
activate the plugin
roundcube -> settings -> aliases 

/var/www/roundcubemail/logs/errors

> [25-Oct-2017 22:44:03 Europe/Berlin] PHP Parse error:  syntax error, unexpected 'factory' (T_STRING), expecting variable (T_VARIABLE) or '$' in /var/www/sources/git/roundcubemail/plugins/aliases/lib/drivers/sql.php on line 27

Set the correct mysql login data doesn't change anything ...
I also tried to change back to 1.3.0 (git checkout tags/1.3.0).

My system:
----------
Debian 8.9 (all updates)
PHP 5.6.30-0+deb8u1
Roundcubemail 1.3.1 [GIT 20170904.2049]

Regards
erdo

**Comment by gianlucagiacometti** [comment]
New release just uploaded
